// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bekiut-og/Icon.tsx": () => import("../components/mockups/bekiut-og/Icon.tsx"),
  "./components/mockups/bekiut-og/Tagline.tsx": () => import("../components/mockups/bekiut-og/Tagline.tsx"),
  "./components/mockups/bekiut-og/Wordmark.tsx": () => import("../components/mockups/bekiut-og/Wordmark.tsx"),
  "./components/mockups/favicon-options/FaviconOptions.tsx": () => import("../components/mockups/favicon-options/FaviconOptions.tsx")
};
